import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Krei</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
            <h1>Sign in for User</h1>
            <form action="">
                <label htmlFor="name">Name</label><br />
                <input type="text" id='name'placeholder='Name'/>
                <br />
                <label htmlFor="username">Username</label><br />
                <input type="text" id='username'placeholder='Username'/>
                <br />
                <label htmlFor="phone">Phone</label><br />
                <input type="tel" id='phone'placeholder='Phone'/>
                <br />
                <label htmlFor="email">Email</label><br />
                <input type="email" id='email' placeholder='Email'/>
                <br />
                <label htmlFor="password">Password</label><br />
                <input type="password" id='password'placeholder='Password'/>
                <br />
                <label htmlFor="re-enterpassword">Re-enterpassword</label><br />
                <input type="text" id='re-enterpassword'placeholder='Re-enterpassword'/>
                <br />
                <input type="submit" />
            </form>
        </div>
        <div>
          <a href="/signin_artist"><button>sign up Artist</button></a>
          <a href="/login_artist"><button>login Artist</button></a>
          <a href="/signin_user"><button>sign up user</button></a>
          <a href="/login_user"><button>login user</button></a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
